const config = {
  title: "Pablo Ramos",
  description: "Frontend Developer",
  project1Banner: "/Images/valobrainBanner.jpg",
  project2Banner: "/Images/myBlogBanner.jpg",
  project3Banner: "/Images/myPortfolioBanner.jpg",
  project4Banner: "/Images/giuseppeBanner.jpg",
  project5Banner: "https://via.placeholder.com/300",
  project6Banner: "/Images/gecommBanner.jpg",
  project1BannerMobile: "/Images/valobrainBanner.jpg",
  project2BannerMobile: "/Images/myBlogBanner.jpg",
  project3BannerMobile: "/Images/myPortfolioBanner.jpg",
  project4BannerMobile: "/Images/giuseppeBanner.jpg",
  project5BannerMobile: "https://via.placeholder.com/300",
  project6BannerMobile: "/Images/gecommBanner.jpg",
  project1Github: "https://github.com/pabloramoss/valo-brain",
  project2Github: "https://github.com/pabloramoss/my-blog",
  project3Github: "https://github.com/pabloramoss/New-portfolio",
  project4Github: "https://via.placeholder.com/300",
  project5Github: "https://via.placeholder.com/300",
  project6Github: "https://github.com/pabloramoss/Gecomm",
  project1Url: "https://valobrain.vercel.app/",
  project2Url: "https://rpablog.vercel.app/",
  project3Url: "https://portfoliopabloramos.vercel.app",
  project4Url: "https://via.placeholder.com/300",
  project5Url: "https://via.placeholder.com/300",
  project6Url: "https://ecommerce-pablo.vercel.app/",
  project1Tech: ["REACT JS","CHAKRA-UI", "YOUTUBE API"],
  project2Tech: ["NEXT.JS", "CHAKRA-UI","MARKDOWN"],
  project3Tech: ["NEXTS.JS", "CHAKRA-UI", "FRAMER-MOTION"],
  project4Tech: ["NEXT.JS", "CHAKRA-UI","AXIOS", "SSR"],
  project5Tech: ["NEXT.JS", "CHAKRA-UI","AXIOS", "SSR"],
  project6Tech: ["NEXT.JS", "CHAKRA-UI","AXIOS", "SSR"],
  project1Description: "Gaming app for Valorant which consists in a video search engine from a specific YouTube channel.",
  project2Description: "Zero cost e-commerce, since it has a database of products and sales made in Google Sheet.",
  project3Description: "Own blog where I share my experiences working with different technologies.",
  project4Description: "My humble portfolio, made it with love. 3D with SketchUp, rendered with TwinMotion, animations with After Effects",
  project5Description: "",
  project6Description: "",
  siteUrl: "https://portfoliopabloramos.vercel.app",
  twitter: "https://twitter.com/rpablo_dev",
  github: "https://github.com/pabloramoss",
  linkedin: "https://www.linkedin.com/in/pabloramoss/",
  aboutTitle: "Who am I?",
  hardTechTitle: "Hard skills",
  softTechTitle: "Soft skills",
  futureTitle: "Future plans",
  about: "I am a frontend developer, passionate for learning about any kind of technology, always trying to improve my skills challenging myself. Currently working with React (especially with NextJS). Hope you found here who you are looking for. Greetings!",
  hardTech: "HTML, CSS, Javascript, Typescript, React, Next.js, Chakra-UI, Framer-motion, MongoDB, Git, Github, Figma, Photoshop.",
  softTech: "Comunication, teamwork, flexibility, creativity, time management, planification.",
  future: "My goal is keep improving my frontend and UI/UX skills. Also, I would like to learn everything related to web3 like Solidity, Web3.js, Ether.js, etc.",
  telegram: "https://tttttt.me/pablooramoss",
  cv: ""
};

export default config;