const config = {
  title: "Pablo Ramos",
  description: "Frontend Developer",
  project1Banner: "/Images/valobrainBanner.jpg",
  project2Banner: "/Images/myBlogBanner.jpg",
  project3Banner: "/Images/myPortfolioBanner.jpg",
  project4Banner: "/Images/giuseppeBanner.jpg",
  project5Banner: "https://via.placeholder.com/300",
  project6Banner: "/Images/gecommBanner.jpg",
  project1Github: "https://github.com/pabloramoss/valo-brain",
  project2Github: "https://github.com/pabloramoss/my-blog",
  project3Github: "https://github.com/pabloramoss/portfolio",
  project4Github: "https://via.placeholder.com/300",
  project5Github: "https://via.placeholder.com/300",
  project6Github: "https://github.com/pabloramoss/Gecomm",
  project1Url: "https://valobrain.vercel.app/",
  project2Url: "https://rpablog.vercel.app/",
  project3Url: "https://pabloramos.vercel.app/",
  project4Url: "https://via.placeholder.com/300",
  project5Url: "https://via.placeholder.com/300",
  project6Url: "https://ecommerce-pablo.vercel.app/",
  project1Tech: ["VITE", "CHAKRA-UI", "AXIOS"],
  project2Tech: ["NEXT.JS", "CHAKRA-UI","MARKDOWN"],
  project3Tech: ["VITE", "CHAKRA-UI"],
  project4Tech: ["NEXT.JS", "CHAKRA-UI","AXIOS", "SSR"],
  project5Tech: "https://via.placeholder.com/300",
  project6Tech: "https://ecommerce-pablo.vercel.app/",
  siteUrl: "https://pabloramos.vercel.app",
  twitter: "https://twitter.com/rpablo_dev",
  github: "https://github.com/pabloramoss",
  linkedin: "https://www.linkedin.com/in/pablo-ramos-9019a0230/",
  aboutTitle: "Acerca de mi",
  hardTechTitle: "Habilidades técnicas",
  softTechTitle: "Habilidades blandas",
  futureTitle: "Planes a futuro",
  about: "Me dedico al desarrollo de aplicaciones web. Me especializo en desarrollo frontend con React. Me gusta involucrarme en proyectos nuevos, aprender nuevas tecnologías, resolver problemas complejos y optimizar procesos.",
  hardTech: "HTML, CSS, Javascript, Typescript, React, React-Testing-Library, Next.js, Chakra-UI, Framer-motion, Node.js, MongoDB, Firebase Auth y Firestore, Express, Git, Github, Figma, Photoshop",
  softTech: "Comunicación, trabajo en equipo, flexibilidad, creatividad, gestión del tiempo, planificación",
  future: "Mi objetivo es seguir especializándome en frontend y UI/UX. Otro objetivo es aprender todo lo relacionado con web3 como programación con Solidity, Web3.js, .Ether.js, etc.",
  telegram: "https://tttttt.me/pablooramoss",
  cv: ""
};

export default config;